name = "nari-workers-relay"
main = "src/index.ts"
compatibility_date = "2025-06-12"

compatibility_flags = ["nodejs_compat"]

routes = [
  # 반드시 custom_domain = true
  { pattern = "wss-relay.nari-web.com", custom_domain = true }
]

[observability.logs]
enabled = true

# This will deploy the project by default to openai-workers-relay.<username>.workers.dev. 
# You can modify this by changing the name of the project in wrangler.toml, 
# and/or setting the `routes` param in this file. Learn more at 
# https://developers.cloudflare.com/workers/configuration/routing/routes/#set-up-a-route-in-wranglertoml 

[[kv_namespaces]]
binding = "NARI_KV"
id = "f2b4ac37ab1f48d498d979e350f433e0"
